import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../services/websocket_service.dart';
import '../utils/constants.dart';
import '../widgets/app_toast.dart';
import '../widgets/glass_text_field.dart';
import '../widgets/web_form_widgets.dart';
import 'chat_screen.dart';

class JoinRoomTab extends StatefulWidget {
  const JoinRoomTab({super.key});

  @override
  State<JoinRoomTab> createState() => _JoinRoomTabState();
}

class _JoinRoomTabState extends State<JoinRoomTab> {
  final TextEditingController _usernameController = TextEditingController();
  final TextEditingController _roomCodeController = TextEditingController();

  bool _isJoining = false;

  void _joinRoom() {
    if (_isJoining) return;

    final username = _usernameController.text.trim();
    final roomCode = _roomCodeController.text.trim();

    if (username.isEmpty || roomCode.isEmpty) {
      _showError('Username and Room Code required!');
      return;
    }

    // Room codes are 6-char alphanumeric, generated by the backend.
    if (roomCode.length != 6 ||
        !RegExp(r'^[a-zA-Z0-9]{6}$').hasMatch(roomCode)) {
      _showError('Room code must be exactly 6 alphanumeric characters.');
      return;
    }

    setState(() => _isJoining = true);

    WebSocketService.instance.connect(username, roomCode);

    WebSocketService.instance.socket.once('room joined', (data) {
      if (!mounted) return;
      setState(() => _isJoining = false);

      int initialCount = 1;
      int? maxUsers;
      if (data is Map) {
        final raw =
            data['user_count'] ??
            data['userCount'] ??
            data['users'] ??
            data['count'] ??
            data['members'];
        if (raw is int && raw > 0) {
          initialCount = raw;
        } else if (raw is List) {
          initialCount = raw.isNotEmpty ? raw.length : 1;
        } else {
          final n = int.tryParse(raw?.toString() ?? '');
          if (n != null && n > 0) initialCount = n;
        }

        final rawMax =
            data['max_users'] ??
            data['maxUsers'] ??
            data['max_members'] ??
            data['maxMembers'] ??
            data['capacity'];
        if (rawMax is int && rawMax > 0) {
          maxUsers = rawMax;
        } else {
          final n = int.tryParse(rawMax?.toString() ?? '');
          if (n != null && n > 0) maxUsers = n;
        }
      } else if (data is int && data > 0) {
        initialCount = data;
      }

      if (maxUsers != null && maxUsers > 0 && initialCount > maxUsers) {
        WebSocketService.instance.disconnect();
        _showError('Room is full ($maxUsers members max).');
        return;
      }

      Navigator.push(
        context,
        PageRouteBuilder<void>(
          transitionDuration: const Duration(milliseconds: 450),
          reverseTransitionDuration: const Duration(milliseconds: 350),
          pageBuilder: (ctx, a1, a2) => ChatScreen(
            username: username,
            roomCode: roomCode,
            initialMemberCount: initialCount,
            maxUsers: maxUsers ?? 0,
          ),
          transitionsBuilder: (ctx, a1, a2, child) {
            final fade = CurvedAnimation(parent: a1, curve: Curves.easeOut);
            final slide = Tween<Offset>(
              begin: const Offset(0.06, 0),
              end: Offset.zero,
            ).animate(CurvedAnimation(parent: a1, curve: Curves.easeOutCubic));
            return FadeTransition(
              opacity: fade,
              child: SlideTransition(position: slide, child: child),
            );
          },
        ),
      );
    });

    WebSocketService.instance.socket.once('invalid room', (_) {
      if (!mounted) return;
      setState(() => _isJoining = false);
      _showError('Room "$roomCode" does not exist.');
    });

    WebSocketService.instance.socket.once('room full', (_) {
      if (!mounted) return;
      setState(() => _isJoining = false);
      WebSocketService.instance.disconnect();
      _showError('Room is full. Maximum member limit reached.');
    });

    WebSocketService.instance.socket.once('connect_error', (_) {
      if (!mounted) return;
      setState(() => _isJoining = false);
      _showError('Failed to connect to server.');
    });
  }

  void _showError(String message) => AppToast.show(context, message);

  @override
  void dispose() {
    _usernameController.dispose();
    _roomCodeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final keyboardInset = MediaQuery.of(context).viewInsets.bottom;
    final isKeyboardOpen = keyboardInset > 0;
    final double bottomPadding =
        keyboardInset > 0 ? keyboardInset + 8.0 : 32.0;

    return SingleChildScrollView(
      physics: const ClampingScrollPhysics(),
      padding: EdgeInsets.fromLTRB(0, 8, 0, bottomPadding),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // ── AnnoRooms badge ───────────────────────────────────────────
              const AnnoBadge(),

              // ── SVG icon (hidden when keyboard is open) ───────────────────
              Visibility(
                visible: !isKeyboardOpen,
                maintainState: true,
                maintainAnimation: true,
                maintainSize: true,
                child: SvgPicture.asset(
                  'lib/assets/Icons/join_room.svg',
                  width: 56,
                  height: 56,
                  colorFilter: const ColorFilter.mode(
                    AppColors.webRed,
                    BlendMode.srcIn,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),

          WebTextField(
            controller: _usernameController,
            placeholder: 'username (max 8)',
            icon: Icons.person_outline,
            maxLength: 8,
          ),
          const SizedBox(height: 14),
          WebTextField(
            controller: _roomCodeController,
            placeholder: 'room id',
            icon: Icons.vpn_key_outlined,
          ),
          const SizedBox(height: 18),

          // ── Footer: hint + button ─────────────────────────────────────
          FormFooter(
            hint: 'Enter your details to join an existing anonymous room.',
            buttonText: _isJoining ? 'Joining...' : 'join',
            onTap: _joinRoom,
          ),
        ],
      ),
    );
  }
}
